[package]
name = "benchmark"
version = "0.1.0"
authors = ["Brandon Falk <bfalk@gamozolabs.com>"]
edition = "2018"

[dependencies]
debugger = { path = "../../libs/debugger" }

[profile.release]
debug = true
